enum actionsConst {
  CALC_CHANGE_INPUT_TEXT = 'CALC_CHANGE_INPUT_TEXT',
  CALC_RESET_RESULT = 'CALC_RESET_RESULT',
  CALC_RESET_TEXT_DISPLAY = 'CALC_RESET_TEXT_DISPLAY',
  CALC_RESET_DISPLAY = 'CALC_RESET_DISPLAY',
  CALC_SIGN_ACTION = 'CALC_SIGN_ACTION ',
  CALC_CHANGE_SIGN_ACTION  = 'CALC_CHANGE_SIGN_ACTION',
  CALC_CALCULATE = 'CALC_CALCULATE',
  CALC_NULL_PROC = 'CALC_NULL_PROC',
  CALCULATE_SIGN = 'CALCULATE_SIGN',
  CALCULATE_ACTION_CHANGE = 'CALCULATE_ACTION_CHANGE',
  CALCULATE_INTEREST = 'CALCULATE_INTEREST',
  ADD_HISTORY_ITEMS = 'ADD_HISTORY_ITEMS',
  HISTORY_LOAD = 'HISTORY_LOAD',
};

export default actionsConst;