export const CALC_CHANGE_INPUT_TEXT = 'CALC_CHANGE_INPUT_TEXT';
export const CALC_RESET_RESULT = 'CALC_RESET_RESULT';
export const CALC_RESET_TEXT_DISPLAY = 'CALC_RESET_TEXT_DISPLAY';
export const CALC_RESET_DISPLAY = 'CALC_RESET_DISPLAY';
export const CALC_SIGN_ACTION = 'CALC_SIGN_ACTION ';
export const CALC_CHANGE_SIGN_ACTION  = 'CALC_CHANGE_SIGN_ACTION';
export const CALC_CALCULATE = 'CALC_CALCULATE';
export const CALC_NULL_PROC = 'CALC_NULL_PROC';

//Для саги
export const CALCULATE_SIGN = 'CALCULATE_SIGN';
export const CALCULATE_ACTION_CHANGE = 'CALCULATE_ACTION_CHANGE';
export const CALCULATE_INTEREST = 'CALCULATE_INTEREST';

export const ADD_HISTORY_ITEMS = 'ADD_HISTORY_ITEMS';
export const HISTORY_LOAD = 'HISTORY_LOAD';
export const HISTORY_ERROR = 'HISTORY_ERROR';